services:
  - type: web
    name: dashmesh-auto-ai
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: VERIFY_TOKEN
        value: DashmeshProperties2026
      - key: WHATSAPP_PHONE_NUMBER_ID
        value: "1239464059243498"
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        value: "2124558472274062"
      - key: WHATSAPP_NUMBER
        value: "919270277281"
      - key: OWNER_ALERT_PHONE
        value: "+918421077613"
      - key: META_ACCESS_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
